DROP DATABASE IF EXISTS occupationservice;
DROP USER IF EXISTS `occupation_service`@`%`;
CREATE DATABASE IF NOT EXISTS occupationservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `occupation_service`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `occupationservice`.* TO `occupation_service`@`%`;
FLUSH PRIVILEGES;

